version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: email-redis
    ports:
      - "6380:6379"  # Changed from 6379 to 6380
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: email-mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/tmp
    volumes:
      - mailhog_data:/tmp

  postgres:
    image: postgres:15-alpine
    container_name: email-postgres
    ports:
      - "5433:5432"  # Changed from 5432 to 5433
    environment:
      - POSTGRES_DB=email_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
  mailhog_data:
  postgres_data:
